# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gp21411.us-east-1

      # User/password auth
      user: MANMEETRANGOOLA
      password: 23W@heguru07

      role: MANMEETRANGOOLA
      database: SANDBOX
      warehouse: REPORTING
      schema: MANMEETRANGOOLA
      threads: 1 
      client_session_keep_alive: False
      query_tag: dbt 

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
